### ISSUE TITLE
[dave] resource requirements for all microservices K8S

### ISSUE THREAD

**Issue by klml** [it-at-m/helm-charts#136]
The Helm Chart defines resource [requirements and limits exclusively for the backend](https://github.com/it-at-m/helm-charts/blob/main/charts/dave/charts/backend/values.yaml#L72). This information is missing for the three portals, which makes reliable resource planning more difficult and can lead to unexpected bottlenecks. 

## Solution 

* uncomment in https://github.com/it-at-m/helm-charts/blob/main/charts/dave/charts/frontend/values.yaml#L72 etc

**Comment by gislab-augsburg** [comment]
@klml two questions:
1. The three portals, you mean admin-portal, frontend, selfservice-portal? I would suggest to define the resources also for the fifth chart, eai. Ok?
2. I would take the request and limit values which dave-public is currently running with in LHM OpenShift. I guess it is running fine there with the current values? This also includes changing the value of cpu requests for backend to 100m (due to LHM limitations). Ok?

**Comment by klml** [comment]
> The three portals, you mean admin-portal, frontend, selfservice-portal? I would suggest to define the resources also for the fifth chart, eai. Ok?

thx, you are right ;)

**Comment by klml** [comment]
> I would take the request and limit values which dave-public is currently running with in LHM OpenShift. I guess it is running fine there with the current values? This also includes changing the value of cpu requests for backend to 100m (due to LHM limitations). Ok?

also yes. Please reduce backend `requests:     cpu: 1500m` 😨 this is far too high.

**Comment by gislab-augsburg** [comment]
https://github.com/gislab-augsburg/helm-charts/commit/0b6565367a080663ee281d9510d3558b12ce8afe

**Comment by gislab-augsburg** [comment]
@klml 
I packed both issues in PR https://github.com/it-at-m/helm-charts/pull/139
Lint test in PR fails:
`✖︎ dave => (version: "0.0.11", path: "charts/dave") > chart version not ok. Needs a version bump! `
Should we change the version?

**Comment by klml** [comment]
>  Should we change the version?

yes always bump the version

**Comment by gislab-augsburg** [comment]
> yes always bump the version
done

**Comment by martind260** [comment]
This is a duplicate to https://github.com/it-at-m/dave/issues/2. For a solution please refer to this issue.

**Comment by klml** [comment]
@martind260 https://github.com/it-at-m/dave/issues/2 is for VMS, this issue is for K8S

**Comment by martind260** [comment]
@klml Is this issue solved? Can I help in any way?

**Comment by klml** [comment]
> Is this issue solved?

No, we still have a different ressources setting between [backend](https://github.com/it-at-m/helm-charts/blob/main/charts/dave/charts/backend/values.yaml#L72) and [frontend](https://github.com/it-at-m/helm-charts/blob/main/charts/dave/charts/frontend/values.yaml#L72).

**Comment by martind260** [comment]
This issue is internally addressed with https://jira.muenchen.de/browse/FV-441

**Comment by martind260** [comment]
The values are now configured (see https://github.com/it-at-m/helm-charts/blob/main/charts/dave/charts/admin-portal/values.yaml#L72)
